StLouisTravel/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisTravel.Models
{
    public class Location : IModel
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Region { get; set; }
        public int Id { get; set; }
        public string Description { get; set; }
        public virtual List<Feedback> Ratings { get; set; }
        public virtual List<CategoryLocation> CategoryLocations { get; set; }
    }
}

StLouisTravel/ViewModels/Locations/CreateLocationViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using StLouisTravel.Data;
using StLouisTravel.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisTravel.ViewModels.Locations
{
    public class CreateLocationViewModel
    {
        [Required(ErrorMessage = "Location Name Required")]
        public string Name { get; set; }

        public string Address { get; set; }

        [Required(ErrorMessage = "Region is Required")]
        public string Region { get; set; }

        public int Id { get; set; }

        [Display(Name = "Select one or more categories")]
        public List<int> CategoryIds { get; set; }
        public List<Category> Categories { get; set; }

        [Required(ErrorMessage = "Please enter a description")]
        [StringLength(maximumLength: 200, MinimumLength = 2, ErrorMessage = "Must be between 2 and 200 characters" )]
        public string Description { get; set; }
            
                     

        public CreateLocationViewModel() { }

        public CreateLocationViewModel(RepositoryFactory factory)
        {
            this.Categories = factory.GetCategoryRepository()
                .GetModels()               
                .ToList();
        }


        public void Persist(RepositoryFactory repositoryFactory)
        {
            Models.Location location = new Models.Location
            {
                Name = this.Name,
                Address = this.Address,
                Region = this.Region,
                Description = this.Description
            };
            
            List<CategoryLocation> locationCategories = CreateManyToManyRelationships(location.Id);
            location.CategoryLocations = locationCategories;
            repositoryFactory.GetLocationRepository().Save(location);
        }

        private List<CategoryLocation> CreateManyToManyRelationships(int locationId)
        {
            return CategoryIds.Select(catId => new CategoryLocation { LocationId = locationId, CategoryId = catId }).ToList();
        }

        internal void ResetCategoryList(RepositoryFactory factory)
        {
            this.Categories = factory.GetCategoryRepository()
               .GetModels()
               .ToList();
        }
    }
    }

StLouisTravel/ViewModels/Locations/DetailsLocationViewModels.cs
using Microsoft.AspNetCore.Mvc;
using StLouisTravel.Data;
using StLouisTravel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using StLouisTravel.ViewModels.Feedbacks;
using StLouisTravel.ViewModels.Categories;

namespace StLouisTravel.ViewModels.Locations
{
    public class DetailsLocationViewModels
    {
        public static DetailsLocationViewModels GetDetails(RepositoryFactory factory, int id)
        {
            
            Location location = factory.GetLocationRepository()
                .GetById(id);

            List<Feedback> feedbackDetails = factory.GetFeedbackRepository()
                .GetModels()
                .Where(f => f.LocationId == id)
                .ToList();

            List<CategoryLocation> categoriesLocators = factory.GetCategoryLocationRepository()
                .GetModels()
                .Where(c => c.LocationId == id)
                .ToList();
            List<Category> allCategories = factory.GetCategoryRepository()
                .GetModels()
                .ToList();
            List<CategoryListDetailViewModel> categories = new List<CategoryListDetailViewModel>();
            foreach(Category allCategory in allCategories)
            {
                foreach(CategoryLocation categoriesLocator in categoriesLocators)
                {
                    CategoryListDetailViewModel cats = new CategoryListDetailViewModel();
                    if (allCategory.Id == categoriesLocator.CategoryId)
                    {
                        cats.CatName = allCategory.Name;
                        
                        categories.Add(cats);
                    }
                }
            }
            List<FeedbackListViewModel> feedbackDetailsViewModel = new List<FeedbackListViewModel>();

            foreach(Feedback feedbackDetail in feedbackDetails)
            {
                FeedbackListViewModel feedbacks = new FeedbackListViewModel();
                feedbacks.Rating = feedbackDetail.Rating;
                feedbacks.Review = feedbackDetail.Review;
                feedbackDetailsViewModel.Add(feedbacks);
            }
            return new DetailsLocationViewModels()
            {
                Name = location.Name,
                Address = location.Address,
                Region = location.Region,
                Description = location.Description,
                Id = location.Id,
                Feedbacks = feedbackDetailsViewModel,
                Categories = categories
            };

            //return factory.GetLocationRepository()
            //    .GetById(locationId)
            //    .Select(l => new DetailsLocationViewModels(l));



        }

        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        public string Name { get; set; }
        public string Address { get; set; }
        public string Region { get; set; }
        public string Description { get; set; }
        public virtual List<FeedbackListViewModel> Feedbacks { get; set; }
        public virtual List<CategoryLocation> CategoriesLocations { get; set; }
        public virtual List<CategoryListDetailViewModel> Categories { get; set; }
       

      
    }
}

StLouisTravel/ViewModels/Locations/EditLocationViewModel.cs
using StLouisTravel.Data;
using StLouisTravel.Models;
using StLouisTravel.ViewModels.Categories;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisTravel.ViewModels.Locations
{
    public class EditLocationViewModel
    {
        private readonly RepositoryFactory repositoryFactory;

        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
        public string Address { get; set; }
        [Required(ErrorMessage = "Region is required")]
        public string Region { get; set; }
        [Required(ErrorMessage = "Description is required")]
        [StringLength(maximumLength: 200, MinimumLength = 2, ErrorMessage = "Must be between 2 and 200 characters")]
        public string Description { get; set; }
        [Display(Name = "Select one or more categories")]
        public List<int> CategoryIds { get; set; }
        public List<Category> Categories { get; set; }
        public List<CategoryListViewModel> Selected { get; set; }
        public List<CategoryListViewModel> Unselected { get; set; }

        public EditLocationViewModel() { }

       

        public EditLocationViewModel(int id, RepositoryFactory repositoryFactory)
        {
            Location location = repositoryFactory.GetLocationRepository().GetById(id);
            List<CategoryLocation> categoriesLocators = repositoryFactory.GetCategoryLocationRepository()
                .GetModels()
                .Where(c => c.LocationId == id)
                .ToList();
             Name = location.Name;
             Address = location.Address;
             Region = location.Region;
             Description = location.Description;
             CategoryIds = categoriesLocators.Select(cat => cat.CategoryId).ToList();
             Categories = repositoryFactory.GetCategoryRepository()
               .GetModels()
               .ToList();

            //List<CategoryListViewModel> selected = new List<CategoryListViewModel>();
            //List<CategoryListViewModel> unselected = new List<CategoryListViewModel>();

            //foreach(var category in Categories)
            //{
            //    foreach(var categoryId in CategoryIds)
            //    {
            //        CategoryListViewModel cat = new CategoryListViewModel();
            //        if (categoryId == category.Id)
            //        {
            //            cat.Name = category.Name;
            //            cat.Id = category.Id;
            //            selected.Add(cat);
            //        }
                 
            //    }
            //}

            //Selected = selected;
            //Unselected = unselected;
        }

        public void Update(int id, RepositoryFactory repositoryFactory)
        {
            Models.Location location = new Models.Location
            {
                Id = id,
                Name = this.Name,
                Address = this.Address,
                Region = this.Region,
                Description = this.Description,
                
        };
            List<CategoryLocation> locationCategories = CreateManyToManyRelationships(location.Id, repositoryFactory);
            location.CategoryLocations = locationCategories;
            repositoryFactory.GetLocationRepository().Update(location);
        }
        private List<CategoryLocation> CreateManyToManyRelationships(int locationId, RepositoryFactory repositoryFactory)
        {
            List<Models.CategoryLocation> cats =
                repositoryFactory.GetCategoryLocationRepository()
                .GetModels()
                .Where(s => s.LocationId == locationId)
                .ToList();
            foreach (var item in cats)
            {
                repositoryFactory.GetCategoryLocationRepository().DeleteMany(item);
            }

            return CategoryIds
                .Select(catId => new Models.CategoryLocation { LocationId = locationId, CategoryId = catId })
                .ToList();
        }
        internal void ResetCategoryList(RepositoryFactory factory)
        {
            this.Categories = factory.GetCategoryRepository()
               .GetModels()
               .ToList();
        }
    }
}

StLouisTravel/ViewModels/Locations/ListLocationViewModel.cs
using Microsoft.AspNetCore.Mvc;
using StLouisTravel.Data;
using StLouisTravel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace StLouisTravel.ViewModels.Locations
{
    public class ListLocationViewModel
    {
        public static List<ListLocationViewModel> GetLocations(RepositoryFactory factory)
        {
            return factory.GetLocationRepository()
                .GetModels()
                //.Include(m => m.Ratings)
                .Select(m => new ListLocationViewModel(m))
                .ToList();
           
        }

        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        public string Name { get; set; }
        public string Address { get; set; }  
        public string Region { get; set; }
        public string Description { get; set; }
        public double AverageRating { get; set; }
        public int NumberOfRatings { get; set; }

        public ListLocationViewModel(Location location)
        {
            this.Id = location.Id;
            this.Name = location.Name;
            this.Address = location.Address;
            this.Region = location.Region;
            this.Description = location.Description;
            if (location.Ratings.Count() == 0)
            {
                this.AverageRating = 0;
            }
            else
            {
                this.AverageRating = Math.Round(location.Ratings.Average(x => x.Rating));
            }
                //this.AverageRating = location.Ratings.Count >= 0 ? Math.Round(location.Ratings.Average(x => x.Rating), 2).ToString() : "none";
                this.NumberOfRatings = location.Ratings.Count;
        }
    }
}

StLouisTravel/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StLouisTravel.Data;
using StLouisTravel.Models;
using StLouisTravel.ViewModels.Feedbacks;

namespace StLouisTravel.Controllers
{
    public class FeedbackController : Controller
    {
        private RepositoryFactory repositoryFactory;

        public FeedbackController(RepositoryFactory repositoryFactory)
        {
            this.repositoryFactory = repositoryFactory;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create(int locationId)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(int locationId, FeedbackCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            model.Persist(repositoryFactory);
            return RedirectToAction(controllerName: nameof(Location), actionName: nameof(Index));
        }

    
    }
}

StLouisTravel/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StLouisTravel.Models;
using StLouisTravel.Data;
using StLouisTravel.ViewModels.Locations;

namespace StLouisTravel.Controllers
{
    public class LocationController : Controller
    {

        private RepositoryFactory repositoryFactory;

        public LocationController(RepositoryFactory repositoryFactory)
        {
            this.repositoryFactory = repositoryFactory;
        }

        public IActionResult Index()
        {
            List<ListLocationViewModel> movies = ListLocationViewModel.GetLocations(repositoryFactory);
            return View(movies);
        }

        [HttpGet]
        public IActionResult Create()
        {

            CreateLocationViewModel model = new CreateLocationViewModel(repositoryFactory);
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(CreateLocationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.ResetCategoryList(repositoryFactory);
                return View(model);
            }

            model.Persist(repositoryFactory);
            return RedirectToAction(actionName: nameof(Index));
        }

        [HttpGet]
        public IActionResult Details(int id)
        {

            DetailsLocationViewModels detailsViewModel = DetailsLocationViewModels.GetDetails(repositoryFactory, id);
            return View(detailsViewModel);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            return View(model: new EditLocationViewModel(id, repositoryFactory));
        }

        [HttpPost]
        public IActionResult Edit(int id, EditLocationViewModel location )
        {
            if (!ModelState.IsValid)
            {
                location.ResetCategoryList(repositoryFactory);
                return View(location);
            }
            location.Update(id, repositoryFactory);
            return RedirectToAction(actionName: nameof(Index));
        }
  


    }
}

StLouisTravel/Views/Location/Create.cshtml
@model StLouisTravel.ViewModels.Locations.CreateLocationViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Travel St. Louis</h1>

<h4>Add Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <select asp-for="Region" class="form-control">
                    <option>Downtown</option>
                    <option>Midtown</option>
                    <option>Dogtown</option>
                    <option>Central West End</option>
                    <option>South City</option>
                    <option>North City</option>
                    <option>The Grove</option>
                    <option>The Hill</option>
                    <option>Soulard</option>
                    <option>University City</option>
                    <option>Metro East</option>
                    <option>West County</option>
                    <option>South County</option>
                    <option>North County</option>

                </select>
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryIds" class="control-label"></label>
                @foreach (var category in Model.Categories)
                {
                   <div>
                       <table class="table">
                           <thead>
                               <tr>
                                <th>
                    <label>@category.Name</label>
                                    </th>
                                   </tr>
                               </thead>
                           <tbody>
                            <td>
                    <input type="checkbox" name="CategoryIds" value="@category.Id" />
                                </td>
                           </tbody>
                           </table>
                    </div>
                }
            </div>
           
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StLouisTravel/Views/Location/Create2.cshtml
@model StLouisTravel.Models.Location

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StLouisTravel/Views/Location/Details.cshtml
@model StLouisTravel.ViewModels.Locations.DetailsLocationViewModels

@{
    ViewData["Title"] = "Details";
}
<div class="text-center">
    <h1>Travel St. Louis</h1>
    </div>
    <div>
        <h4>Details</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Region)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Region)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            @foreach (var item in Model.Categories)
            {
              <dt class="col-sm-2">
                  @Html.DisplayNameFor(model => model.Categories)
              </dt>  
             <dd class="col-sm-10">
               @Html.DisplayFor(modelItem => item.CatName)
             </dd>
                             
            }
</div>
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Ratings
                    </th>
                    <th>
                        Reviews
                    </th>
                </tr>
            </thead>



            @foreach (var item in Model.Feedbacks)
            {
                <tbody>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Review)
                </td>
                </tbody>
            }

          


        </table>

    </div>



    <div>
        <a asp-controller="Feedback" asp-action="Create" asp-route-locationID="@Model.Id">Add Feedback</a> |
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Index">Back to List</a> |
    </div>

StLouisTravel/Views/Location/Edit.cshtml
@model StLouisTravel.ViewModels.Locations.EditLocationViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EditLocationViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <select asp-for="Region" class="form-control">
                    <option>Downtown</option>
                    <option>Midtown</option>
                    <option>Dogtown</option>
                    <option>Central West End</option>
                    <option>South City</option>
                    <option>North City</option>
                    <option>The Grove</option>
                    <option>The Hill</option>
                    <option>Soulard</option>
                    <option>University City</option>
                    <option>Metro East</option>
                    <option>West County</option>
                    <option>South County</option>
                    <option>North County</option>

                </select>
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryIds" class="control-label"></label>
                @foreach (var category in Model.Categories)
                {
                    <label>@category.Name</label>
                    @if (Model.CategoryIds.Contains(category.Id))
                    {
                        <input type="checkbox" name="CategoryIds" value="@category.Id" checked />
                    }
                    else
                    {
                        <input type="checkbox" name="CategoryIds" value="@category.Id" />
                    }
                }
            </div>
</div>
</div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

StLouisTravel/Views/Location/Index.cshtml
@model IEnumerable<StLouisTravel.ViewModels.Locations.ListLocationViewModel>

@{
    ViewData["Title"] = "Index";
}
<div class="text-center">
    <h1>Travel St. Louis</h1>
    <h3>Locations</h3>
</div>


<p>
    <a asp-action="Create">Add Location</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AverageRating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfRatings)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Details", "Location", new { id = item.Id })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AverageRating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfRatings)
            </td>
            <td>
                |<a asp-action="Edit" asp-route-id="@item.Id">Edit</a>|
                |@Html.ActionLink("Rate", "Create", "Feedback", new { locationId = item.Id })|
                |<a asp-action="Details" asp-route-id="@item.Id">Details</a>|
                |<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>|
            </td>
        </tr>
}
    </tbody>
</table>